#!/bin/sh
down() {
wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%-
volume=$(wpctl get-volume @DEFAULT_SINK@ | cut -d ' ' -f 2 | awk '{print $1 * 100 "%"}')
dunstify -a "VOLUME" "Decreasing to $volume" -h int:value:"$volume" -i audio-volume-low-symbolic -r 2593 -u normal
canberra-gtk-play -i dialog-error -d "error"
}

up() {
wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+
volume=$(wpctl get-volume @DEFAULT_SINK@ | cut -d ' ' -f 2 | awk '{print $1 * 100 "%"}')
dunstify -a "VOLUME" "Increasing to $volume" -h int:value:"$volume" -i audio-volume-high-symbolic -r 2593 -u normal
canberra-gtk-play -i dialog-error -d "error"
}

mute() {
muted="$(wpctl get-volume @DEFAULT_SINK@ | cut -d ' ' -f 3)"
if $muted; then
  wpctl set-mute @DEFAULT_SINK@ 1
  dunstify -a "VOLUME" "UNMUTED" -i audio-volume-high-symbolic -r 2593 -u normal
else 
  wpctl set-mute @DEFAULT_SINK@ 0
  dunstify -a "VOLUME" "MUTED" -i audio-volume-muted-symbolic -r 2593 -u normal
fi
}

micmute() {
micmuted="$(wpctl get-volume @DEFAULT_SOURCE@ | cut -d ' ' -f 3)"
if $micmuted; then
  wpctl set-mute @DEFAULT_SOURCE@ 1
  dunstify -a "VOLUME" "UNMUTED" -i audio-input-microphone-high -r 2593 -u normal
else
  wpctl set-mute @DEFAULT_SOURCE@ 0
  dunstify -a "VOLUME" "MUTED" -i audio-input-microphone-muted -r 2593 -u normal
fi
}

case "$1" in
  up) up;;
  down) down;;
  mute) mute;;
  micmute) micmute;;
esac
