# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# Opacity 
#windowrulev2 = opacity 0.90 0.90,class:^(brave-browser)$
#windowrulev2 = opacity 0.80 0.80,class:^(Steam)$
#windowrulev2 = opacity 0.80 0.80,class:^(steam)$
#windowrulev2 = opacity 0.80 0.80,class:^(steamwebhelper)$
#windowrulev2 = opacity 0.80 0.80,class:^(Spotify)$
#windowrulev2 = opacity 0.80 0.80,class:^(Code)$
#windowrulev2 = opacity 0.80 0.80,class:^(org.kde.dolphin)$
#windowrulev2 = opacity 0.80 0.80,class:^(file-roller)$
#windowrulev2 = opacity 0.80 0.80,class:^(nwg-look)$
#windowrulev2 = opacity 0.80 0.80,class:^(qt5ct)$
#windowrulev2 = opacity 0.80 0.80,class:^(discord)$ #Discord-Electron
#windowrulev2 = opacity 0.80 0.80,class:^(WebCord)$ #WebCord-Electron
#windowrulev2 = opacity 0.80 0.70,class:^(pavucontrol)$
windowrulev2 = opacity 0.80 0.70,class:^(org.kde.polkit-kde-authentication-agent-1)$
#windowrulev2 = opacity 0.80 0.80,class:^(org.telegram.desktop)$

# Position
windowrulev2 = float,class:^(org.kde.polkit-kde-authentication-agent-1)$
windowrulev2 = float,class:^(pavucontrol)$
windowrulev2 = float,title:^(Media viewer)$
windowrulev2 = float,title:^(Volume Control)$
windowrulev2 = float,title:^(Picture-in-Picture)$
windowrulev2 = float,class:^(Viewnior)$
windowrulev2 = float,title:^(DevTools)$
windowrulev2 = float,class:^(file_progress)$
windowrulev2 = float,class:^(confirm)$
windowrulev2 = float,class:^(dialog)$
windowrulev2 = float,class:^(download)$
windowrulev2 = float,class:^(notification)$
windowrulev2 = float,class:^(error)$
windowrulev2 = float,class:^(confirmreset)$
windowrulev2 = float,title:^(Open File)$
windowrulev2 = float,title:^(branchdialog)$
windowrulev2 = float,title:^(Confirm to replace files)
windowrulev2 = float,title:^(File Operation Progress)
windowrulev2 = float,title:^(New Download)$
windowrulev2 = float,class:^(showmethekey-gtk)$
windowrulev2 = pin,class:^(showmethekey-gtk)$
windowrulev2 = float,title:^(Save File)$
windowrulev2 = float,title:^(Download Complete)$
windowrulev2 = fakefullscreen,class:^(code-url-handler)$
windowrulev2 = float,class:^(xdm-app)$

# kdeconnect presentaion
windowrulev2 = noanim,class:^(org.kde.kdeconnect.daemon)$
windowrulev2 = float,class:^(org.kde.kdeconnect.daemon)$
windowrulev2 = nofullscreenrequest,class:^(org.kde.kdeconnect.daemon)$
windowrulev2 = center,class:^(org.kde.kdeconnect.daemon)$
windowrulev2 = size 100% 100%,class:^(org.kde.kdeconnect.daemon)$
windowrulev2 = nofocus,class:^(org.kde.kdeconnect.daemon)$

# Workspace 
#windowrulev2 = workspace 1, class:^(Brave-browser)$
#windowrulev2 = workspace 2, class:^(discord)$
#windowrulev2 = workspace 3, class:^(org.telegram.desktop)$
#windowrulev2 = workspace 4, class:^(Code)$
#windowrulev2 = workspace 4, class:^(code-url-handler)$
#windowrulev2 = workspace 5, class:^(Spotify)$

# Size
windowrulev2 = size 800 600,class:^(download)$
windowrulev2 = size 800 600,title:^(Open File)$
windowrulev2 = size 800 600,title:^(Save File)$
windowrulev2 = size 800 600,title:^(Volume Control)$
windowrulev2 = size 800 600,title:^(All Files)$
windowrulev2 = idleinhibit focus,class:^(mpv)$
windowrulev2 = idleinhibit fullscreen,class:^(brave-browser)$

# xwaylandvideobridge
windowrulev2 = opacity 0.0 override 0.0 override,class:^(xwaylandvideobridge)$
windowrulev2 = noanim,class:^(xwaylandvideobridge)$
windowrulev2 = nofocus,class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus,class:^(xwaylandvideobridge)$

#steam
windowrulev2 = stayfocused, title:^()$,class:^(steam)$
windowrulev2 = minsize 1 1, title:^()$,class:^(steam)$

